### ISSUE TITLE
[health 3.0.3] Can't access shared_preferences from background service when health package is used 

### ISSUE THREAD

**Issue by arifjmamun** [cph-cachet/flutter-plugins#298]
### Device / Emulator and OS
 - Device: Pixel_3_XL
 - OS: Android 11

### Describe the bug
Normally `shared_prefernces` and `health` package work fine. 
But when I am trying to access `shared_preferences` from background service (`workmanager`) including `health` package installed, it is not working and I am getting the following error.

```
W/FlutterEngine( 4023): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@f7f3415) but could not find and invoke the GeneratedPluginRegistrant.
I/flutter ( 4023): Native called background task: simpleTask
I/flutter ( 4023): null
I/WM-WorkerWrapper( 4023): Worker result SUCCESS for Work [ id=3084fd69-f75c-414a-89f6-e9301f799e34, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
E/flutter ( 4023): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter ( 4023):
```

### To Reproduce
```dart
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:workmanager/workmanager.dart';

void printHello() {
  SharedPreferences.getInstance().then((prefs) {
    print(prefs.getString('hello'));
  });
}

void callbackDispatcher() {
  WidgetsFlutterBinding.ensureInitialized();
  Workmanager.executeTask((task, inputData) {
    print("Native called background task: $task"); //simpleTask will be emitted here.
    print(inputData);
    printHello();
    return Future.value(true);
  });
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final prefs = await SharedPreferences.getInstance();
  await prefs.setString('hello', 'Hello World');
  // print(storage.read('hello'));

  Workmanager.initialize(
    callbackDispatcher,
    isInDebugMode: true,
  );
  Workmanager.registerOneOffTask("1", "simpleTask");
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

### Expected behavior
It should work normally like when I am trying to access the shared_preferences without the `health` package from `workmanager`

### Actual behavior
Getting the following output:
```
W/FlutterEngine( 4023): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@f7f3415) but could not find and invoke the GeneratedPluginRegistrant.
I/flutter ( 4023): Native called background task: simpleTask
I/flutter ( 4023): null
I/WM-WorkerWrapper( 4023): Worker result SUCCESS for Work [ id=3084fd69-f75c-414a-89f6-e9301f799e34, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
E/flutter ( 4023): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter ( 4023):
```
pubspec.yaml
```yaml
name: background
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  health: ^3.0.3
  shared_preferences: ^0.5.12+4
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  workmanager: ^0.2.3
  flutter_barcode_scanner: ^1.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  hive_generator: ^0.8.2
  build_runner: ^1.11.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
```

### Flutter doctor 
```
(base) arif@Arifs-MBP ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)
    ! Error: Binate's iPhone 5s is not connected. Xcode will continue when Binate's iPhone 5s is connected. (code -13)

! Doctor found issues in 1 category.
```

### Additional information
When I am trying with comment out the`health` package from `pubspec.yaml` file it works fine. I think it breaks the plugin registration.
